services:
  brick-tracker:
    container_name: brick-tracker
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DB_PATH: /app/data/brick.db
      IMAGE_PATH: /app/data/upload
    env_file:
      - .env
    networks:
      - caddy_public
    volumes:
      - ./brick-tracker-data:/app/data

networks:
  caddy_public:
    driver: bridge
    external: true
    name: "caddy_public"
