services:
  brick-tracker:
    container_name: brick-tracker
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - caddy_public
    volumes:
      - ${DATA_PATH:-./brick-tracker-data}:/app/data
      - ${DB_PATH:-./brick-tracker-data/brick.db}:/app/data/brick.db


networks:
  caddy_public:
    driver: bridge
    external: true
    name: "caddy_public"
